# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' Compute the Gaussian kernel matrix between two samples
#'
#' @param x_mat A matrix containing the observations of X
#' @param y_mat A matrix containing the observations of Y
#' @param H Covariance matrix of the Gaussian kernel
#'
#' @return Matrix of computed Gaussian kernel values 
#'
#' @useDynLib Quadratik
#' @rdname computeKernelMatrix
#' @keywords internal
computeKernelMatrix <- function(x_mat, y_mat, H) {
    .Call('_QuadratiK_computeKernelMatrix', PACKAGE = 'QuadratiK', x_mat, y_mat, H)
}

#' Compute the Poisson kernel matrix between observations in a sample.
#'
#' @param x_mat A matrix containing the observations.
#' @param rho concentration parameter of the Poisson kernel.
#'
#' @return Matrix of computed Poisson kernel values
#'
#' @examples
#' #x <- matrix(rnorm(300),ncol=3)
#' # Normalize each observation
#' #x <- x/sqrt(rowSums(x^2))
#' #computePoissonMatrix(x_mat = x, rho=0.8)
#'
#' @useDynLib Quadratik
#' @rdname computePoissonMatrix
#' @keywords internal
computePoissonMatrix <- function(x_mat, rho) {
    .Call('_QuadratiK_computePoissonMatrix', PACKAGE = 'QuadratiK', x_mat, rho)
}

#' Non-parametric centered kernel
#' 
#' Compute the values of the non-parametric centered kernel given the values of the 
#' kernel matrix. 
#'
#' @param kmat_zz A matrix containing the values of the kernel functions for each pair of observations
#' @param n_z The number of total observations
#'
#' @return Matrix of centered kernel
#'
#' @examples
#' #h <- 0.5
#' #H <- h^2*diag(2)
#' #x <- matrix(rnorm(100), ncol = 2) #50 x 2
#' #y <- matrix(rnorm(100), ncol = 2) #50 x 2
#' #k_mat <- computeKernelMatrix(x, y, H) #50 x 50
#' #NonparamCentering(k_mat, 50)
#'
#'
#' @useDynLib Quadratik
#' @rdname NonparamCentering
#' @keywords internal
NonparamCentering <- function(kmat_zz, n_z) {
    .Call('_QuadratiK_NonparamCentering', PACKAGE = 'QuadratiK', kmat_zz, n_z)
}

#' Parametric centered kernel
#' 
#' Compute the Gaussian kernel centered with respect to a Normal distribution
#' with mean vector mu and covariance Sigma
#'
#' @param kmat_zz A matrix containing the values of the kernel functions for each pair of observations
#' @param z_mat Matrix of observations used for computing the kernel matrix
#' @param H Covariance matrix of the Normal kernel
#' @param mu_hat Mean of centering of Normal distribution
#' @param Sigma_hat Covariance of centering Normal distribution
#'
#' @return Matrix of centered kernel
#'
#' @examples
#' #h <- 0.5
#' #H <- h^2*diag(2)
#' #x <- matrix(rnorm(100), ncol = 2)
#' #y <- matrix(rnorm(100), ncol = 2)
#' #z <- rbind(x, y)
#' #mu_hat <- matrix(colMeans(z),nrow=1)
#' #Sigma_hat <- cov(z)
#' #k_mat <- computeKernelMatrix(z, z, H)
#' #ParamCentering(k_mat, z, H, mu_hat, Sigma_hat)
#'
#'
#' @useDynLib Quadratik
#' @rdname ParamCentering
#' @keywords internal
ParamCentering <- function(kmat_zz, z_mat, H, mu_hat, Sigma_hat) {
    .Call('_QuadratiK_ParamCentering', PACKAGE = 'QuadratiK', kmat_zz, z_mat, H, mu_hat, Sigma_hat)
}

#' Compute kernel-based quadratic distance two-sample test with Normal kernel
#'
#' @param x_mat A matrix containing observations from the first sample
#' @param y_mat A matrix containing observations from the second sample
#' @param h The bandwidth parameter for the kernel function
#' @param centeringType String indicating the method used for centering the normal kernel
#' @param mu_hat Mean vector for the reference distribution 
#' @param Sigma_hat Covariance matrix of the reference distribution
#'
#' @return A scalar value representing the test statistic
#'
#' @details 
#' \code{mu_hat} and \code{Sigma_hat} need to be provided even if they are used 
#' only in case of "Param" \code{centeringType}.
#' 
#' @examples
#' #x <- matrix(rnorm(100), ncol = 2)
#' #y <- matrix(rnorm(100), ncol = 2)
#' #mu_hat <- matrix(0,nrow=1)
#' #sigma_hat <- diag(2)
#' #stat2sample(x, y, h = 1, mu_hat=mu_hat, Sigma_hat=sigma_hat)
#'
#' @useDynLib Quadratik
#' @rdname stat2sample
#' @keywords internal
stat2sample <- function(x_mat, y_mat, h, mu_hat, Sigma_hat, centeringType = "Nonparam") {
    .Call('_QuadratiK_stat2sample', PACKAGE = 'QuadratiK', x_mat, y_mat, h, mu_hat, Sigma_hat, centeringType)
}

#' Compute kernel-based quadratic distance test for Normality
#'
#' @param x_mat A matrix containing the observations.
#' @param h The bandwidth parameter for the Gaussian kernel function.
#' @param mu_hat Mean vector for the reference distribution (if available)
#' @param Sigma_hat Covariance matrix of the reference distribution (if available)
#' @param centeringType String indicating the method used for centering the normal kernel ('Param' or 'Nonparam').
#'
#' @return A scalar value representing the test statistic.
#'
#' @examples
#' #x <- matrix(rnorm(100), ncol = 2)
#' #h=1
#' 
#' #mu_hat = matrix(rep(0,2),nrow=1)
#' #sigma_hat = diag(2)
#' #kbNormTest(x, h, mu_hat=mu_hat, Sigma_hat=sigma_hat ,centeringType = "Param")
#'
#' @useDynLib Quadratik
#' @rdname kbNormTest
#' @keywords internal
kbNormTest <- function(x_mat, h, mu_hat, Sigma_hat, centeringType = "Param") {
    .Call('_QuadratiK_kbNormTest', PACKAGE = 'QuadratiK', x_mat, h, mu_hat, Sigma_hat, centeringType)
}

#' Poisson kernel-based test for Uniformity on the Sphere
#' 
#' Compute the Poisson kernel-based test for Uniformity given a sample of observations on the Sphere
#'
#' @param x_mat A matrix containing the observations.
#' @param rho Concentration parameter of the Poisson kernel.
#'
#' @return Vector with the values of the U-statistic and V-statistic
#'
#' @examples
#' #x <- matrix(rnorm(300),ncol=3)
#' # Normalize each observation
#' #x <- x/sqrt(rowSums(x^2))
#' #statPoissonUnif(x, rho=0.7)
#'
#' @useDynLib Quadratik
#' @rdname statPoissonUnif
#' @keywords internal
statPoissonUnif <- function(x_mat, rho) {
    .Call('_QuadratiK_statPoissonUnif', PACKAGE = 'QuadratiK', x_mat, rho)
}

#' Kernel-based quadratic distance k-sample tests
#' 
#' Compute the kernel-based quadratic distance k-sample tests with the Normal kernel and bandwidth parameter h.
#'
#' @param x A matrix containing observations from the pooled sample, from the k samples.
#' @param y A vector containing observations' memberships to the k samples.
#' @param h The bandwidth parameter for the kernel function.
#' @param sizes Vector with sample sizes of the considered samples
#' @param cum_size Vector indicating the cumulative sizes, adding one sample at the time.
#'
#' @return A vector containing the two k-sample test statistics
#'
#' @examples
#' #x1 <- matrix(rnorm(200), ncol = 2)
#' #x2 <- matrix(rnorm(200), ncol = 2)
#' #x3 <- matrix(rnorm(200, 2), ncol = 2)
#' #x <- rbind(x1, x2, x3)
#' #y <- rep(c(1,2,3), each=100)
#' #sizes <- as.vector(table(y))
#' #cum_size <- c(0,cumsum(sizes))
#' #stat_ksample_cpp(x, y, h = 1, sizes, cum_size)
#'
#' @useDynLib Quadratik
#' @rdname stat_ksample_cpp
#' @keywords internal
stat_ksample_cpp <- function(x, y, h, sizes, cum_size) {
    .Call('_QuadratiK_stat_ksample_cpp', PACKAGE = 'QuadratiK', x, y, h, sizes, cum_size)
}

